##
## Copyright (c) 2023 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
##
## NVIDIA CORPORATION, its affiliates and licensors retain all intellectual
## property and proprietary rights in and to this material, related
## documentation and any modifications thereto. Any use, reproduction,
## disclosure or distribution of this material and related documentation
## without an express license agreement from NVIDIA CORPORATION or
## its affiliates is strictly prohibited.
##
# /home/ubuntu/Downloads/curobo/src/curobo/content/assets/robot/ur_description/ur5_leap.urdf
robot_cfg:
  kinematics:
    use_root_pose: True
    hand_pose_transfer_path: "hand_pose_transfer/leap.yml"
    usd_path: "robot/leap_description/leap.usd"
    usd_robot_root: "/robot"
    isaac_usd_path: ""
    usd_flip_joints: {}
    usd_flip_joint_limits: []

    urdf_path: "robot/leap_tac3d/leap_tac3d.urdf"
    asset_root_path: "robot/leap_tac3d"
    
    base_link: "rh_palm_lower"
    ee_link: "rh_fingertip_1"
    link_names: ['rh_finger1_tip_center', 'rh_finger2_tip_center', 'rh_finger3_tip_center', 'rh_thumb_tip_center']
    lock_joints: null
    extra_links: null

    collision_link_names: ['rh_palm_lower', 
      'rh_mcp_joint', 'rh_pip', 'rh_dip', 'rh_fingertip_base', 'rh_fingertip_1', 
      'rh_mcp_joint_2', 'rh_pip_2', 'rh_dip_2', 'rh_fingertip_base_2', 'rh_fingertip_2',
      'rh_mcp_joint_3', 'rh_pip_3', 'rh_dip_3', 'rh_fingertip_base_3', 'rh_fingertip_3',
      'rh_pip_4', 'rh_thumb_dip', 'rh_thumb_fingertip_base', 'rh_thumb_fingertip']
    collision_spheres:
      rh_palm_lower:
        - "center": [-0.04, 0.004, -0.012]
          "radius": 0.025
        - "center": [-0.04, -0.036, -0.012]
          "radius": 0.025
        - "center": [-0.04, -0.076, -0.012]
          "radius": 0.025
        - "center": [-0.075, -0.055, -0.012]
          "radius": 0.025
        - "center": [-0.009, 0.009, -0.012]
          "radius": 0.015
        - "center": [-0.009, -0.037, -0.012]
          "radius": 0.015
        - "center": [-0.009, -0.082, -0.012]
          "radius": 0.015
      rh_mcp_joint:
        - "center": [-0.027, 0.052, 0.014]
          "radius": 0.015
        - "center": [-0.027, 0.032, 0.014]
          "radius": 0.015
      rh_mcp_joint_2:
        - "center": [-0.027, 0.032, 0.014]
          "radius": 0.015
        - "center": [-0.027, 0.052, 0.014]
          "radius": 0.015
      rh_mcp_joint_3:
        - "center": [-0.027, 0.052, 0.014]
          "radius": 0.015
        - "center": [-0.027, 0.032, 0.014]
          "radius": 0.015
      rh_pip:
        - "center": [0.001, 0.0, -0.011]
          "radius": 0.015
        - "center": [0.014, 0.0, -0.011]
          "radius": 0.015
      rh_pip_2:
        - "center": [0.014, 0.0, -0.011]
          "radius": 0.015
        - "center": [0.001, 0.0, -0.011]
          "radius": 0.015
      rh_pip_3:
        - "center": [0.014, 0.0, -0.011]
          "radius": 0.015
        - "center": [0.001, 0.0, -0.011]
          "radius": 0.015
      rh_dip:
        - "center": [0.002, -0.022, 0.015]
          "radius": 0.015
        - "center": [0.002, -0.046, 0.02]
          "radius": 0.015
        - "center": [0.002, -0.046, 0.01]
          "radius": 0.015
        - "center": [0.014, -0.035, 0.015]
          "radius": 0.015
      rh_dip_2:
        - "center": [0.002, -0.022, 0.015]
          "radius": 0.015
        - "center": [0.002, -0.046, 0.02]
          "radius": 0.015
        - "center": [0.002, -0.046, 0.01]
          "radius": 0.015
        - "center": [0.014, -0.035, 0.015]
          "radius": 0.015
      rh_dip_3:
        - "center": [0.002, -0.022, 0.015]
          "radius": 0.015
        - "center": [0.002, -0.046, 0.02]
          "radius": 0.015
        - "center": [0.002, -0.046, 0.01]
          "radius": 0.015
        - "center": [0.014, -0.035, 0.015]
          "radius": 0.015
      rh_fingertip_base:
        - "center": [0.002, -0.032, 0.019]
          "radius": 0.015
        - "center": [0.002, -0.032, 0.009]
          "radius": 0.015
      rh_fingertip_base_2:
        - "center": [0.002, -0.032, 0.019]
          "radius": 0.015
        - "center": [0.002, -0.032, 0.009]
          "radius": 0.015
      rh_fingertip_base_3:
        - "center": [0.002, -0.032, 0.019]
          "radius": 0.015
        - "center": [0.002, -0.032, 0.009]
          "radius": 0.015
      rh_pip_4:
        - "center": [-0.005, 0.0, -0.012]
          "radius": 0.015
      rh_thumb_dip:
        - "center": [0.0, 0.002, -0.014]
          "radius": 0.015
        - "center": [0.0, 0.022, -0.014]
          "radius": 0.015
      rh_thumb_fingertip_base:
        - "center": [0.0, -0.002, -0.014]
          "radius": 0.015
        - "center": [0.0, -0.01, -0.014]
          "radius": 0.015
        - "center": [0.002, -0.03, -0.009]
          "radius": 0.015
        - "center": [0.002, -0.03, -0.019]
          "radius": 0.015
        - "center": [0.002, -0.05, -0.009]
          "radius": 0.015
        - "center": [0.002, -0.05, -0.019]
          "radius": 0.015

      rh_fingertip_1:
        - "center": [0.0, 0.038, 0.009]
          "radius": 0.01
        - "center": [0.0, 0.038, 0.002]
          "radius": 0.017
      rh_fingertip_2:
        - "center": [0.0, 0.038, 0.009]
          "radius": 0.01
        - "center": [0.0, 0.038, 0.002]
          "radius": 0.017
      rh_fingertip_3:
        - "center": [0.0, 0.038, 0.009]
          "radius": 0.01
        - "center": [0.0, 0.038, 0.002]
          "radius": 0.017
      rh_thumb_fingertip:
        - "center": [0.0, 0.0355, 0.01]
          "radius": 0.01
        - "center": [0.0, 0.0355, 0.003]
          "radius": 0.017
       
    collision_sphere_buffer: 0.0
    extra_collision_spheres: {}
    self_collision_ignore: {
      'rh_palm_lower' : ['rh_mcp_joint', 'rh_mcp_joint_2', 'rh_mcp_joint_3', 'rh_pip_4', 'rh_thumb_dip'],
      'rh_mcp_joint' : ['rh_pip'],
      'rh_pip' : ['rh_dip'],
      'rh_dip' : ['rh_fingertip_base'],
      'rh_fingertip_base' : ['rh_fingertip_1'],
      'rh_fingertip_1': [],

      'rh_mcp_joint_2' : ['rh_pip_2'],
      'rh_pip_2': ['rh_dip_2'],
      'rh_dip_2' : ['rh_fingertip_base_2'],
      'rh_fingertip_base_2' : ['rh_fingertip_2'],
      'rh_fingertip_2': [],

      'rh_mcp_joint_3' : ['rh_pip_3'],
      'rh_pip_3' : ['rh_dip_3'], 
      'rh_dip_3' : ['rh_fingertip_base_3'],
      'rh_fingertip_base_3' : [rh_fingertip_3],
      'rh_fingertip_3': [],

      'rh_pip_4' : ['rh_thumb_dip'],
      'rh_thumb_dip' : ['rh_thumb_fingertip_base'],
      'rh_thumb_fingertip_base' : [rh_thumb_fingertip],
      'rh_thumb_fingertip': []
    }
    self_collision_buffer: {
      'rh_palm_lower' : 0,
      'rh_mcp_joint' : 0,
      'rh_pip' : 0,
      'rh_dip' : 0,
      'rh_fingertip_base' : 0,
      'rh_fingertip_1': 0.002,

      'rh_mcp_joint_2' : 0,
      'rh_pip_2': 0,
      'rh_dip_2' : 0,
      'rh_fingertip_base_2' : 0,
      'rh_fingertip_2' : 0.002,

      'rh_mcp_joint_3' : 0,
      'rh_pip_3' : 0, 
      'rh_dip_3' : 0,
      'rh_fingertip_base_3' : 0,
      'rh_fingertip_3': 0.002,

      'rh_pip_4' : 0,
      'rh_thumb_dip' : 0,
      'rh_thumb_fingertip_base' : 0,
      'rh_thumb_fingertip': 0.002
    }

    use_global_cumul: True
    mesh_link_names:
      [
        'rh_palm_lower' ,

        'rh_mcp_joint' ,
        'rh_pip' ,
        'rh_dip' ,
        'rh_fingertip_base' ,
        'rh_fingertip_1',

        'rh_mcp_joint_2' ,
        'rh_pip_2',
        'rh_dip_2' ,
        'rh_fingertip_base_2' ,
        'rh_fingertip_2',

        'rh_mcp_joint_3' ,
        'rh_pip_3' , 
        'rh_dip_3' ,
        'rh_fingertip_base_3' ,
        'rh_fingertip_3',

        'rh_pip_4' ,
        'rh_thumb_dip' ,
        'rh_thumb_fingertip_base',
        'rh_thumb_fingertip'
      ]

    cspace:
      joint_names: ['rh_joint_12', 'rh_joint_13', 'rh_joint_14', 'rh_joint_15', 
                    'rh_joint_1', 'rh_joint_0', 'rh_joint_2', 'rh_joint_3', 
                    'rh_joint_5', 'rh_joint_4', 'rh_joint_6', 'rh_joint_7',
                    'rh_joint_9', 'rh_joint_8', 'rh_joint_10', 'rh_joint_11']
      # retract_config: [0.0, -1.0471975511965976, 1.3089969389957472, 1.3089969389957472, 1.5707963267948966, 0.0, 0.5, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0] # List[float]
      retract_config: [-0.5, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0] # List[float]
      # retract_config: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0] # List[float]
      null_space_weight: [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
      cspace_distance_weight: [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
      max_jerk: 500.0
      max_acceleration: 15.0
